<?php

namespace Database\Seeders;

use App\Models\Area;
use App\Models\Booking;
use App\Models\Customer;
use App\Models\Room;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Create User
        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        // 2. Create Areas
        $areas = [
            ['name' => 'SALA Sarina', 'address' => 'District 2, HCMC', 'description' => 'Luxury apartment complex'],
            ['name' => 'SALA Sarica', 'address' => 'District 2, HCMC', 'description' => 'Modern living space'],
            ['name' => 'SALA Sadora', 'address' => 'District 2, HCMC', 'description' => 'Green living environment'],
        ];

        foreach ($areas as $areaData) {
            $area = Area::create($areaData);

            // 3. Create Rooms for each Area
            $roomTypes = ['Studio', '1BR', '2BR', 'Penthouse'];
            $statuses = ['available', 'occupied', 'maintenance'];

            for ($i = 1; $i <= 10; $i++) {
                Room::create([
                    'area_id' => $area->id,
                    'code' => strtoupper(substr($area->name, 5, 3)) . '-' . str_pad($i, 3, '0', STR_PAD_LEFT),
                    'type' => $roomTypes[array_rand($roomTypes)],
                    'price' => rand(500, 2000), // Random price
                    'status' => $statuses[array_rand($statuses)],
                    'description' => 'Fully furnished room with city view.',
                ]);
            }
        }

        // 4. Create Customers
        Customer::factory(20)->create();

        // 5. Create Bookings
        $customers = Customer::all();
        $rooms = Room::all();

        foreach ($customers as $customer) {
            if (rand(0, 1)) { // 50% chance to have a booking
                $room = $rooms->random();
                Booking::create([
                    'customer_id' => $customer->id,
                    'room_id' => $room->id,
                    'check_in' => now()->subDays(rand(1, 30)),
                    'check_out' => now()->addDays(rand(1, 30)),
                    'price' => $room->price,
                    'deposit' => $room->price * 0.1,
                    'status' => 'confirmed',
                    'notes' => 'Generated by seeder',
                ]);
            }
        }
    }
}
